name: cv25s_final
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy>=1.20.0
      - scipy>=1.7.0
      - opencv-python>=4.5.0
      - open3d>=0.16.0
      - pillow>=9.0.0
